[package]
name = "sketchybar-helper-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sketchybar_helper_rs"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach2 = "0.4.1"
rand = "0.8.5"
